[package]
name = "getdata"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
reqwest = { version = "0.12.9", features = ["blocking"] }
thiserror = "2.0.8"

[lints]
workspace = true
