[package]
name = "aoc2024"
version.workspace = true
edition.workspace = true
publish = false
rust-version = "1.82"

[workspace]
members = ["crates/*"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
clap = { version = "4.5.22", features = ["derive"] }
derive-new = { version = "0.7.0", default-features = false }
inline_colorization = "0.1.6"

[dependencies]
aoc-parse = "0.2.18"
clap.workspace = true
counter = "0.6.0"
derive-new.workspace = true
derive_more = { version = "1.0.0", features = ["add", "from", "mul"] }
grid = "0.15.0"
inline_colorization.workspace = true
itertools = "0.13.0"
rayon = { version = "1.10.0", optional = true }
regex = { version = "1.11.1", default-features = false }
strum = { version = "0.26.3", features = ["derive"] }

[features]
default = ["par"]
par = ["dep:rayon"]

[lints]
workspace = true

[lib]
doctest = false

[profile.release]
debug = 1
