[alias]
alldays = "run --release --package alldays"
clippy-all = "clippy --all-targets --all-features --workspace"
day = "run --release --bin"
newday = "run --release --package newday --"
getdata = "run --release --package getdata --"